logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
server:
    port: 8000
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password:
        url: jdbc:mysql://localhost:3306/kids-care?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    mvc:
        hidden-method:
            filter:
                enabled: true
#    sql:
#        init:
#            mode: always
